### ISSUE TITLE
Exception when launching hunt

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [mila-udem/orion#120]
Some strange exception. What is happening there?

Before, I did `orion init_only` on a different machine.

```bash
$ orion -vv hunt -n omni26
DEBUG:orion.core.io.resolve_config:[Errno 2] No such file or directory: '/opt/user/conda/share/orion.core/orion_config.yaml.example'
DEBUG:orion.core.io.resolve_config:[Errno 2] No such file or directory: '/etc/xdg/orion.core/orion_config.yaml'
DEBUG:orion.core.io.resolve_config:[Errno 2] No such file or directory: '/opt/user/conda/share/orion.core/orion_config.yaml.example'
DEBUG:orion.core.io.resolve_config:[Errno 2] No such file or directory: '/etc/xdg/orion.core/orion_config.yaml'
DEBUG:orion.core.io.experiment_builder:Creating mongodb database client with args: {'name': 'test', 'host': '....'}
DEBUG:orion.core.worker.experiment:Creating Experiment object with name: omni26
INFO:orion.core.io.experiment_builder:{'name': 'omni26', 'max_trials': inf, 'pool_size': 10, 'algorithms': 'random', 'database': {'name': 'test', 'type': 'mongodb', 'host': '...'}, 'debug': False, 'auto_resolution': False, 'algorithm_change': False, 'user_args': [], 'leafs': [], 'metadata': {'orion_version': 'v0.1.0', 'user': 'serdyuk'}}
INFO:orion.core.io.experiment_builder:{'name': 'omni26', 'max_trials': inf, 'pool_size': 10, 'algorithms': 'random', 'database': {'name': 'test', 'type': 'mongodb', 'host': '...'}, 'debug': False, 'auto_resolution': False, 'algorithm_change': False, 'user_args': [], 'leafs': [], 'metadata': {'orion_version': 'v0.1.0', 'user': 'serdyuk'}}
DEBUG:orion.core.worker.experiment:Creating Experiment object with name: omni26
DEBUG:orion.core.worker.experiment:Creating Experiment object with name: omni26
WARNING:orion.core.worker.experiment:Found section 'debug' in configuration. Experiments do not support this option. Ignoring.
WARNING:orion.core.worker.experiment:Found section 'auto_resolution' in configuration. Experiments do not support this option. Ignoring.
WARNING:orion.core.worker.experiment:Found section 'algorithm_change' in configuration. Experiments do not support this option. Ignoring.
WARNING:orion.core.worker.experiment:Found section 'user_args' in configuration. Experiments do not support this option. Ignoring.
WARNING:orion.core.worker.experiment:Found section 'leafs' in configuration. Experiments do not support this option. Ignoring.
Traceback (most recent call last):
  File "/opt/user/conda/bin/orion", line 11, in <module>
    sys.exit(main())
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/cli/__init__.py", line 39, in main
    orion_parser.execute(argv)
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/cli/base.py", line 71, in execute
    function(args)
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/cli/hunt.py", line 53, in main
    experiment = EVCBuilder().build_from(args)
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/io/evc_builder.py", line 51, in build_from
    experiment = ExperimentBuilder().build_from(cmdargs)
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/io/experiment_builder.py", line 239, in build_from
    experiment = self.build_from_config(full_config)
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/io/experiment_builder.py", line 270, in build_from_config
    experiment.configure(config)
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/worker/experiment.py", line 410, in configure
    final_config = experiment.configuration
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/worker/experiment.py", line 349, in configuration
    config[attrname] = attribute.configuration
AttributeError: 'str' object has no attribute 'configuration'
```

**Comment by dmitriy-serdyuk** [comment]
`attribute` is a string 'random'
```
ipdb> attribute
'random'
```

**Comment by bouthilx** [comment]
Yes it's a problem I run into yesterday. This happens when you try to run an experiment without script arguments but the database cannot be found in the database.

**Comment by dmitriy-serdyuk** [comment]
What cannot be found? database looks fine, I just substituted my db link with `...`

**Comment by bouthilx** [comment]
The experiment cannot be found in the database. I might be wrong however.

The problem is the KeyError catch silenced [here](https://github.com/mila-udem/orion/blob/develop/src/orion/core/worker/experiment.py#L543). You can add the following snippet in the except.
```python
import traceback
traceback.trace_exc()
```
It will print a traceback once, that's fine and that is why the catch is there. The second time it fails however, and I predict it will, is indicative of what is wrong. Please print the output here. I can help with it.

**Comment by dmitriy-serdyuk** [comment]
```
Traceback (most recent call last):
  File "/opt/user/conda/lib/python3.6/site-packages/orion/core/worker/experiment.py", line 532, in _instantiate_config
    space = space_builder.build_from(config['metadata']['user_args'])
KeyError: 'user_args'
```

**Comment by bouthilx** [comment]
That's the second one right? Then it looks like it was not found in the database, 'user_args' would be set otherwise at the second time.

In a python shell, you can try
```python
from orion.core.io.experiment_builder import ExperimentBuilder
experiment_view = ExperimentBuilder().build_view_from({'name': 'omni26'})
```
To see if the experiment exist, otherwise:
```python
from orion.core.io.database import Database
database = Database(name='test', type='mongodb', host='....')
experiments = database.read('experiments', {})
print("\n".join(sorted(e['name'] for e in experiments)))
```

**Comment by bouthilx** [comment]
ok, thank you for the log.

I started to write a fix for a better error message and a command to list the available experiments in the database. I'll be slowed down because of ICML but I hope I can make the PR before next week.

**Comment by dmitriy-serdyuk** [comment]
Ok, the problem was that in docker I was under root account.
